Fixes for Cordova Android build 2.5.0.0
wevote/WebApp pull request #4117
Opened 2024-10-15 23:08 UTC by SailingSteve

Still need to get Sign in with Twitter working
Some more removal of stripe calls.
Some snyk fixes
Removed a listener from OrganizationModal.jsx on close. 
"Fixed" the missing address on the ready page for mobile devices and Cordova.

2024-10-17 00:11 UTC, DaleMcGrew requested changes

2024-10-17 00:11 UTC, DaleMcGrew commented on src/js/common/components/CampaignSupport/PayToPromoteProcess.jsx
> -        <PaymentWrapper>
Hi @SailingSteve we actually are using this code for a UX test and can't strip this out at this time. I'd rather leave PayToPromoteProcess untouched this close to the election. I'm happy to jump on a screenshare if you have any questions.

2024-10-17 00:11 UTC, DaleMcGrew commented on src/js/pages/More/Donate.jsx
> -                          <PaymentCenteredWrapper>
I'd also like to leave this page unchanged this close to the election. This code shouldn't be reachable on our live site, but there are too many moving parts to make this change right now.

2024-10-30 18:37 UTC, SailingSteve commented
Replaced by https://github.com/wevote/WebApp/pull/4157

2024-10-30 18:37 UTC, closed without merging