Automated 7 test cases of Donate page
wevote/WebApp pull request #4120
Opened 2024-10-16 18:47 UTC by dolbi-digital

List of test cases:
Verify the Donate page will appear after clicking the Donate link.
Verify text and donation widget are loaded
Verify link "Our budgets are small" link.
Verify one-time predefined payment with Write us a comment option.
Verify Monthly Custom payment with "Display your donation & comment on the donor wall" option.
Verify Quaterly predefined payment with "Dedicate my donation in honor or in memory of someone" option.
Verify Annually Custom payment with all options.

2024-10-17 02:51 UTC, fdiazq requested changes

2024-10-17 02:51 UTC, fdiazq commented on tests/browserstack_automation/page_objects/donate.page.js
> +    return $('//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/span[1]');
Could you add an id for this element instead of searching for the div.

2024-10-17 02:51 UTC, fdiazq commented on tests/browserstack_automation/page_objects/donate.page.js
> +    return $('//label[@for="plan_duration_one_time"]');
Could you add an id for this element.

2024-10-17 02:51 UTC, fdiazq commented on tests/browserstack_automation/page_objects/donate.page.js
> +    return $('//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/span[1]');
For all locators that do not have id could revise the pull request to include id's for all locator functions

2024-10-22 16:18 UTC, dolbi-digital commented on tests/browserstack_automation/page_objects/donate.page.js
> +    return $('//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/span[1]');
Added ids where it possible, simplified selectors

2024-10-22 16:20 UTC, dolbi-digital commented on tests/browserstack_automation/page_objects/donate.page.js
> +    return $('//label[@for="plan_duration_one_time"]');
Fixed 
$('#plan_duration_one_time')

2024-10-23 01:56 UTC, fdiazq approved these changes
👍 @dolbi-digital

2024-10-23 01:58 UTC, merged

2024-10-23 02:32 UTC, fdiazq commented
@dolbi-digital  I recommend utilizing a linter such as ESLint in your next pull request to fix formatting warnings.

2024-10-23 03:52 UTC, dolbi-digital commented
@fdiazq Thanks! Sure! I will.