[Issue #WV-737] Update, Refactor, and Fix Issues in Discuss Page
wevote/WebApp pull request #4155
Opened 2024-10-30 07:26 UTC by snysmymric

### What github.com/wevote/WebApp/issues does this fix?
[[WV-737] [Web] Update, Refactor, and Fix Issues in Available Discuss Page Tests ](https://wevoteusa.atlassian.net/browse/WV-737)

[Web] Update, Refactor, and Fix Issues in Available Discuss Page Tests
### Changes included this pull request?
*Added missing get() methods to discuss.page.js:
   signInTitle
   signInSubtitle
   textTestAuthor
   termsWrapper
   testImoniaAuthor
   openTermsOfService
   openPrivacyPolicy
   avatarCard
   voterEmailAddressHelperText
   voterEmailAddressLabel
* Deleted duplicate test case D_024
* Deleted the deprecated test D_016 nonLatinLetterEmailVerification as it is not applicable according to support for IDN (Internationalized Domain Name) and email addresses.
* Corrected the order of test numbering to match the document with test cases.
* Added new test D_002 verifyDiscussPageSpellingSignIn to check spelling on the sign-in window of the Discuss page.
* Added new test D_008 verifyTabKeySelectEmailCancelButton to check the functionality of the Cancel button when using the Tab key.
* Updated tests D_006, D_013, D_014, D_015, D_017, D_018, D_019, D_020, and D_021:
   Removed unnecessary timeouts.
   Added additional checks for the displayed/not displayed error message and its color.
* Reworked test D_026 for Chrome and Safari browsers:
   Chrome checks for whitespace in email input and prevents entry.
   Safari does not enforce this restriction.

2024-10-30 19:33 UTC, fdiazq requested changes
@snysmymric Could you add id's for the get functions that utilize class name to locate elements?

2024-11-12 20:21 UTC, snysmymric commented
@fdiazq
Done! As we discussed, I've updated the await driver.switchWindow in all the tests within the "Discuss" folder. I've run the tests with these changes on BrowserStack (localhost:3000). You can view my test results using the following link:
[BrowserStack Test Results](https://observability.browserstack.com/projects/Default%2BProject/builds/Anna%3A/93?tab=tests&status=passed)

2024-11-13 04:10 UTC, fdiazq approved these changes

2024-11-13 04:11 UTC, fdiazq commented
@snysmymric 👍

2024-11-13 04:11 UTC, merged