WV-652 Challenge About [Team Review]
wevote/WebApp pull request #4181
Opened 2024-11-23 02:49 UTC by Succorro

### What github.com/wevote/WebApp/issues does this fix?
- Challenge About section updates
### Changes included this pull request?
- Fixed SVG styling: the svg was not copied correctly resulting in improper rendering on the page
- refactored code to match figma screenshot
- created more styled components for easier readability 
- minor styling additions for font weight 
- wired up data from challenge store

2024-11-23 17:15 UTC, DaleMcGrew requested changes
Thank you @Succorro for these changes. I have the following requests for changes before I approve this pull request.
I hope you are having a good weekend.

2024-11-23 17:15 UTC, DaleMcGrew commented on src/js/common/components/Challenge/ChallengeAbout.jsx
> -  const challengeDates = (
Hi @Succorro could you please roll back the challengeDates code to how it was?

2024-11-23 17:15 UTC, DaleMcGrew commented on src/js/common/components/Challenge/ChallengeAbout.jsx
> -        {showStartedBy && (
Please maintain the same place in the code for your new challengeOwners changes, as it was prior to your changes (i.e, the top-to-bottom order). Please support the "showStartedBy" variable -- there are some modes where we won't show this started by section.

2024-11-26 22:53 UTC, Succorro commented
Let me know if there are any more changes needed Dale :thumbsup:

2024-11-28 20:55 UTC, DaleMcGrew commented
Thank you @Succorro! 👍

2024-11-28 20:55 UTC, merged