WV-490 parse politician name and state, render on before load
wevote/WebApp pull request #4205
Opened 2024-12-13 02:28 UTC by omgitsmiles

### What github.com/wevote/WebApp/issues does this fix?

Google  “de-lists” the politician page when there is a delay in retrieving politician information. The information does seem to eventually load, but too late for Google. I parsed the politician name and state from URL to render on suspense before api loads. 

### Changes included this pull request?

- extractPoliticianDetailsFromUrl function pulling politician name and state from URL
- adding a suspense with politician details on load

2024-12-13 14:01 UTC, DaleMcGrew requested changes
This is a good start @omgitsmiles, thank you. Comments included.

2024-12-13 14:01 UTC, DaleMcGrew commented on src/js/compileDate.js.backup
> +module.exports = ['10/9/2024, 5:54:14 PM'];
Please add this compileDate.js.backup file to .gitignore so it isn't checked in.

2024-12-13 14:01 UTC, DaleMcGrew commented on src/js/common/pages/Politician/PoliticianDetailsPage.jsx
> +        <Suspense fallback={(
Hi @omgitsmiles, we don't want to add a different place to display this information, we want the politicianNameParsedFromURLBeforeLoad and politicianStateParsedFromURLBeforeLoad placed into the components where the name and state currently appear once the data loads.

2024-12-13 14:32 UTC, omgitsmiles commented on src/js/common/pages/Politician/PoliticianDetailsPage.jsx
> +        <Suspense fallback={(
Thanks for the clarification. Will update.

2024-12-15 18:53 UTC, DaleMcGrew commented
Thank you @omgitsmiles! 👍

2024-12-15 18:53 UTC, merged